/-
  This module declares a signature for the base modal language,
  i.e. mono-sorted and with a single modal operator.

  Our primitive modal operator is the diamond.
  Box is defined as notation shorthand for diamond.

  We completely preclude any hybridization by further defining
  the base modal language as the *fragment* of the many-sorted polyadic one,
  generated by propositional variables, modal applications, and logical connectives.
  That is: no state variables, no quantification, no @-binding!
-/

import Hybrid.BNF

hybrid_def ModalBase :=
  sort WFF ::= builtin Nat       -- these are constant nominals unf.
  sort WFF ::= "◇"(WFF) [poss]

  -- TODO: Allow declaring propositional variables in the DSL
  -- sort WFF ::= prop p | prop q | prop r
  -- Or maybe:
  -- sort WFF ::= countable prop

def FormulaSort := ModalBase.WFF
